### ISSUE TITLE
Spreminjanje razpona legende na zemljevidu

### ISSUE THREAD

**Issue by klarasirca** [klarasirca/APPR-2020-21#2]
Zanima me, kako lahko spremenim razpon barv in legende na zemljevidu (če je to sploh možno), da bi se na zemljevidu bolje videlo, kakšno je povprečno število priseljenih ljudi na 100.000 prebivalcev po državah, torej da bi bilo barvnih odtenkov več in tudi številskih kategorij več. Trenutno moja koda izgleda tako: (vizualizacija.r - 203 vrstica) Prilagam pa še screenshot zemljevida.
<img width="874" alt="Screenshot 2021-08-27 at 22 36 31" src="https://user-images.githubusercontent.com/49915119/131185859-d97fe09f-f663-4e83-9f5d-8b9a5a56c755.png">

`#povprečne priselitve v državi za leta 2011-19 na 100k - ZEMLJEVID

evropa_priseljevanje_leta <- tabela11 %>% group_by(Leto, Drzava) %>% summarise(Priseljeni=sum(Stevilo))
prebpriseljevanje <- inner_join(evropa_priseljevanje_leta,tabela15)
novo <- prebpriseljevanje %>% mutate(Sprem=(100000/Prebivalstvo)) %>% mutate(Stevilo_pris_na100k = round(Sprem * Priseljeni,0))  
povprecje2 <- novo %>% group_by(Drzava) %>% summarise(Povprečje=mean(Stevilo_pris_na100k)) %>% mutate(Povprečje=round(Povprečje,0))

zemljevid1 <- tm_shape(merge(zemljevid,
                            povprecje2,duplicateGeoms = TRUE,
                             by.x="SOVEREIGNT", by.y="Drzava"), xlim=c(-25,32), ylim=c(32,72)) +
  tm_polygons("Povprečje", title = "Število priseljenih ljudi na 100k") + 
  tm_layout(bg.color = "skyblue") + 
  tm_layout(main.title = "Povprečje števila priseljenih ljudi v državo 2011-19 na 100k prebivalcev", main.title.size = 1, legend.title.size = 2) `

**Comment by timotejvesel** [comment]
V funkcijo `tm_polygons` dodaj parameter `breaks = vektor`, kjer je `vektor` vektor z vrednostmi, ki jih želiš za meje kategorij.

**Comment by klarasirca** [comment]
Hvala, sem popravila.
